language: c
compiler:
  - gcc
  - clang

jobs:
  include:
    - os: linux
    - os: osx
      env: WREN_TARGET_MAC=1

# Travis VMs are 64-bit but we compile both for 32 and 64 bit. To enable the
# 32-bit builds to work, we need gcc-multilib.
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib

dist: trusty

script: ./.travis.sh
